### ISSUE TITLE
Re-publish package on NuGet

### ISSUE THREAD

**Issue by Piedone** [agriffard/TheBootstrapTheme#16]
I see that there was a package but [it's unlisted now](https://www.nuget.org/packages/TheBootstrapTheme.OrchardCore). May I ask why? It would be great to have the theme available from NuGet too.

**Comment by wAsnk** [comment]
When should we expect it to be published on NuGet? @agriffard

**Comment by wAsnk** [comment]
It's up now [https://www.nuget.org/packages/TheBootstrapTheme](https://www.nuget.org/packages/TheBootstrapTheme)

**Comment by Piedone** [comment]
So it's only that the NuGet shield links to the wrong package from the Readme.

**Comment by agriffard** [comment]
ok, link fixed.
